http://localhost:8080/user

--include
--silent

Accept: application/json; 
Connection: keep-alive 
Content-Type: application/json; charset=utf-8 
User-Agent: VRC
#
GET 
{
  "username": "diego",
  "password": "asd"
}
# POST 
# {
#   "username": "diego",
#   "password": "asd"
# }
#
#PUT /6664c47ec7cc107b41a26a14
#{
#  "content": "Nota 2",
#  "title": "Nota 2"
#}
